### ISSUE TITLE
raising struct.error. when number of data is more than items in template

### ISSUE THREAD

**Issue by RavenKyu** [RavenKyu/modbus-command-line-client#1]
when number of data is more than items in template

```bash
(Cmd) read_holding_register -alocalhost -p502 -c10 -tsample
2020-10-05 14:00:38 | request  | 192.168.10.66   > 00 00 00 0a
2020-10-05 14:00:38 | respose  | localhost:502   > 14 55 6e 69 74 32 33 2d 41 ff ff fc 19 ff ff ff fa 80 00 00 00

Traceback (most recent call last):
  File "/Users/limdukkyu/.pyenv/versions/modbusclc/lib/python3.8/site-packages/cliparse/__init__.py", line 40, in _do_command
    spec.func(spec)
  File "/Users/limdukkyu/Works/projects/cli_modbus_client/modbusclc/__init__.py", line 213, in modbus_request
    data = get_data_with_template(result.values[1:], template,
  File "/Users/limdukkyu/Works/projects/cli_modbus_client/modbusclc/__init__.py", line 93, in get_data_with_template
    d = struct.unpack(fmt, bytes.fromhex(data[i][0]))
struct.error: unpack requires a buffer of 4 bytes
(Cmd)
```

**Comment by RavenKyu** [comment]
``` 
no  data type    reg    bytes                value        note
----  -----------  -----  -------------------  -----------  -----------------------
   0  B64_STRING   40001  556e 6974 3233 2d41  Unit23-A     text label
   1  B16_UINT     40005  ffff                 65535        16 bit unsigned integer
   2  B16_INT      40006  fc19                 -999         16 bit integer
   3  B32_UINT     40007  ffff fffa            4294967290   32 bit unsigned integer
   4  B32_INT      40009  8000 0000            -2147483648  32 bit integer
   5  B32_FLOAT    -      -                    -            item exists but no data
   6  B32_FLOAT    -      -                    -            item exists but no data
   7  B32_FLOAT    -      -                    -            item exists but no data
   8  B32_FLOAT    -      -                    -            item exists but no data
   9  B8_UINT      -      -                    -            item exists but no data
  10  B8_INT       -      -                    -            item exists but no data
  11  BIT8         -      -                    -            item exists but no data
  12  BIT8         -      -                    -            item exists but no data
```
